config/routes.rb
Rails.application.routes.draw do

  root  'authors#root'

  resources :authors do

    collection do
      get :search
      get :display
      get :root
    end

  end

  resources :books do

    collection do
      get :search
      get :display
    end

  end

end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :books
  validates_presence_of :author_name

  def self.search(query)
    where("author_name like ?", "%#{query}%")
  end


end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :author

  def self.search(query)
    where("book_name like ?", "%#{query}%")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

	def new
		@author = Author.new
	end

	def create
		@author = Author.new(author_params)
		@author.save

		redirect_to author_path(@author)
	end

  def search
    #render display_author_path
  end

  def display
    @authors  = Author.search(params[:search]).order("author_name")
  end

	def index
      @authors = Author.all.order("author_name")
  end

	def edit
		@author = Author.find(params[:id])
	end

	def update
		@author = Author.find(params[:id])
		@author.update(author_params)

		redirect_to author_path(@author)
  end

  def show
    @author = Author.find(params[:id])
  end


	def destroy
		@author = Author.find(params[:id])
		@author.delete

		redirect_to authors_path
	end

	def author_params
		params.require(:author).permit(:author_name, :sex, :country)
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	def new
		@book = Book.new(author_id: params[:id])			
	end

	def create
		@book = Book.create(book_params)
		
		redirect_to book_path(@book)
  end

  def search

  end

  def show
    @book = Book.find(params[:id])
  end

  def display
    @books  = Book.search(params[:search]).order("book_name")
  end

  def index
      @books = Book.all.order('created_at DESC')
  end

  def edit
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		@book.update(book_params)

		redirect_to book_path(@book)
	end

	def destroy
		@book = Book.find(params[:id])
		@book.delete

		redirect_to books_path
	end

	def book_params
		params.require(:book).permit(:book_name, :author_id, :price)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/display.html.erb
<h4> Displaying search results for Authors </h4>

<head>
  <style>

      table, td, th
      {
          border:2px solid blue;
      }
      th
      {
          background-color: royalblue;
          color:white;
      }
      td, th
      {
          padding:5px;
      }
      tr:nth-child(even) {background-color: white}
      tr:nth-child(odd) {background-color: lightcyan}
  </style>
</head>

<body>
<table>
  <tr>
    <th>Author Name</th>

    <th> ACTION </th>
    <th> ACTION </th>

  </tr>

  <% @authors.each do |author| %>
      <tr>
        <td><%= link_to author.author_name.upcase, author_path(author) %></td>

        <td> <%= link_to "EDIT", edit_author_path(author), :class => 'btn btn-mini btn-warning' %> </td>
        <td> <%= link_to "DELETE", author_path(author), method: :delete, :class => 'btn btn-mini btn-danger' %> </td>
      </tr>
  <% end %>
</table>
</body>

<%= link_to "Go Back to Main Page", root_authors_path %>

app/views/authors/edit.html.erb
<%= form_for @author do |author| %>
    Author's Name : <%= author.text_field :author_name %>   <br> <br>
    Author's Sex : <%= author.select(:sex, %w{ Male Female }, :include_blank => true) %>    <br> <br>
    Author's Country : <%= author.text_field :country %>
    <br> <br>

    <%= author.submit "Update Author" %>
<% end %>

app/views/authors/index.html.erb
<h4> Displaying search results for Authors </h4>

<head>
  <style>

      table, td, th
      {
          border:2px solid blue;
      }
      th
      {
          background-color: royalblue;
          color:white;
      }
      td, th
      {
          padding:5px;
      }
      tr:nth-child(even) {background-color: white}
      tr:nth-child(odd) {background-color: lightcyan}
  </style>
</head>

<body>
<table>
  <tr>
    <th> Name </th>
    <th>Sex </th>
    <th> Country </th>
    <th> ACTION </th>
    <th> ACTION </th>

  </tr>

  <% @authors.each do |author| %>
      <tr>
        <td><%= link_to author.author_name.upcase, author_path(author) %></td>
        <td><%= author.sex %></td>
        <td><%= author.country %></td>

        <td> <%= link_to "EDIT", edit_author_path(author), :class => 'btn btn-mini btn-warning' %> </td>
        <td> <%= link_to "DELETE", author_path(author), method: :delete, :class => 'btn btn-mini btn-danger' %> </td>
      </tr>
  <% end %>
</table>
</body>

app/views/authors/king.html.erb
<%= form_tag(authors_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search authors here" %>
<%= submit_tag "Search", :name => nil %>
<% end %>

app/views/authors/new.html.erb
<%= form_for @author do |author| %>	Author's Name : <%= author.text_field :author_name %>   <br> <br>    Author's Sex : <%= author.select(:sex, %w{ Male Female }, :include_blank => true) %>    <br> <br>    Author's Country : <%= author.text_field :country %>    <br> <br>	<%= author.submit "Create new Author", :class => "btn-info btn-large" %><% end %>

app/views/authors/root.html.erb
<h1> Welcome to Publication </h1>

app/views/authors/search.html.erb
<%= form_tag(display_authors_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search authors here" %>
<%= submit_tag "Search", :name => nil %>
<% end %>

app/views/authors/show.html.erb
Name: <%= @author.author_name.upcase %> <br>
Sex: <%= @author.sex %> <br>
Country: <%= @author.country %> <br>
<hr>
<h4> Displaying search results for Authors </h4>

<head>
  <style>

      table, td, th
      {
          border:2px solid blue;
      }
      th
      {
          background-color: royalblue;
          color:white;
      }
      td, th
      {
          padding:5px;
      }
      tr:nth-child(even) {background-color: white}
      tr:nth-child(odd) {background-color: lightcyan}
  </style>
</head>

<body>
<table>
  <tr>
    <th> Book Name </th>
    <th> Book Price </th>

    <th> ACTION </th>
    <th> ACTION </th>

  </tr>

  <% @author.books.each do |book| %>
      <tr>
        <td><%= book.book_name.upcase %></td>
        <td><%= book.price %></td>
        <td> <%= link_to "EDIT", edit_book_path(book.id), :class => "btn btn-mini btn-warning btn-active" %> </td>
        <td> <%= link_to "DELETE", book_path(book.id), method: :delete, :class => "btn btn-mini btn-danger btn-active" %> </td>
      </tr>
  <% end %>
</table>
</body>

app/views/books/display.html.erb
<h4> Displaying search results for Books </h4>

<head>
  <style>

      table, td, th
      {
          border:2px solid blue;
      }
      th
      {
          background-color: royalblue;
          color:white;
      }
      td, th
      {
          padding:5px;
      }
      tr:nth-child(even) {background-color: white}
      tr:nth-child(odd) {background-color: lightcyan}
  </style>
</head>

<body>
<table>
  <tr>
    <th>Book Name</th>
    <th>Book Price</th>

    <th> ACTION </th>
    <th> ACTION </th>

  </tr>

  <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.book_name.upcase, book_path(book) %></td>
        <td><%= book.price %></td>
        <td> <%= link_to "EDIT", edit_book_path(book), :class => 'btn btn-mini btn-warning' %> </td>
        <td> <%= link_to "DELETE", book_path(book), method: :delete, :class => 'btn btn-mini btn-danger' %> </td>
      </tr>
  <% end %>
</table>
</body>

app/views/books/edit.html.erb
<%= form_for @book do |book| %>
	Book Name: <%= book.text_field :book_name %> <br>
    Price: <%= book.text_field :price, :class => 'price', :value => (number_with_precision(book.object.price, :precision => 2) || 0.00) %>
    <br>
    Select Author: <%= book.select :author_id, Author.all.collect {|p| [p.author_name, p.id]}, {include_blank:true } %> <br>  <br>
    <%= book.submit "Edit Book" %>   <%= link_to 'Go Back ', books_path %>

<% end %>

app/views/books/index.html.erb
<h4> Displaying List of Books </h4>


<head>
<style>
    table, td, th
    {
        border:2px solid blue;
    }
    th
    {
        background-color: royalblue;
        color:white;
    }
    td, th
    {
        padding:5px;
    }
    tr:nth-child(even) {background-color: white}
    tr:nth-child(odd) {background-color: lightcyan}
</style>
</head>

<body>
<table>
  <tr>
    <th>Book Name</th>
    <th>Book Price</th>
    <th> ACTION </th>
    <th> ACTION </th>
  </tr>

  <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.book_name.upcase, book_path(book)  %></td>
        <td><%= book.price  %></td>
        <td> <%= link_to "EDIT", edit_book_path(book), :class => 'btn btn-mini btn-warning' %> </td>
        <td> <%= link_to "DELETE", book_path(book), method: :delete, :class => 'btn btn-mini btn-danger' %> </td>
      </tr>
  <% end %>
</table>
</body>

app/views/books/king.html.erb
<%= form_tag(books_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search books here" %>
<%= submit_tag "Search", :name => nil %>
<% end %>

app/views/books/new.html.erb
<%= form_for @book do |book| %>
	Book Name: <%= book.text_field :book_name %> <br>

    Price: <%= book.text_field :price, :class => 'price', :value => (number_with_precision(book.object.price, :precision => 2) || 0.00) %>
	<br>

    Select Author: <%= book.select :author_id, Author.all.collect {|p| [p.author_name, p.id]}, {include_blank:true } %> <br>
    <br>
    <%= book.submit "Create New Book", :class => "btn-info" %>


<% end %>

app/views/books/search.html.erb
<%= form_tag(display_books_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search books here" %>
<%= submit_tag "Search", :name => nil %>
<% end %>

app/views/books/show.html.erb
<h4> Author of the Book <h3>"<%= @book.book_name.upcase %>"</h3> is <h3>"<%= @book.author.author_name.upcase %>" </h3> </h4>
    <%= link_to "EDIT", edit_book_path(@book), :class => "btn btn-mini btn-warning btn-active" %>
    <%= link_to "DELETE", author_path(@book), method: :delete, :class => "btn btn-mini btn-danger btn-active" %>

    <br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Publication</title>
      <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
      <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css">
      <script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
      <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
      <style type="text/css">
          .bs-example{
              margin: 20px;
          }
      </style>
    </head>
<body>
        <div class="bs-example">
          <ul class="nav nav-pills">
            <li> <%= link_to "Home", root_authors_path %> </li>
            <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">Search <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li> <%= link_to "by Author", search_authors_path %> </li>
              <li> <%= link_to "by Book", search_books_path %> </li>
            </ul>
          </li>

            <li class="dropdown">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">Authors <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Create", new_author_path %> </li>
                <li><%= link_to "Edit / Delete", authors_path %> </li>
              </ul>
            </li>

            <li class="dropdown ">
              <a href="#" data-toggle="dropdown" class="dropdown-toggle">Books <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Create", new_book_path %></a></li>
                <li><%= link_to "Edit / Delete", books_path %></a></li>
              </ul>
            </li>
          </ul>
        </div>
 <hr>
    <div class="span9">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>

  <hr>
    <footer>
      <p>&copy; Company 2014</p>
    </footer>



</body>
</html>